### ISSUE TITLE
Train booking app using mern . 

### ISSUE THREAD

**Issue by MurakondaIndraja** [harsha-vardhan-reddy-07/Train-Booking-App-MERN#1]
Sir my project title is train booking app. In this project  doesn't shows the available trains, book now and bookings. Sir I have observed the all the files any file doesn't shows the train names like rayalaseema express. Sir can you please help me. This project is submitted on the next week sir.

**Comment by harsha-vardhan-reddy-07** [comment]
Hey Indraja, by default there will be no trains in the application. As this is a guided project (not the real time application), you need to register as admin first and then add few trains. Then, those trains will be reflected in the user profile

**Comment by MurakondaIndraja** [comment]
Sir but your demo vedio shows the trains names. Sir these trains are added
in client side or server side. I have create a new file sir. How to create
a new file can please help me sir

**Comment by harsha-vardhan-reddy-07** [comment]
Those names were added from admin panel. As I've mentioned earlier, please login/register as admin and then add trains. You'll see the same in the demo too

**Comment by MurakondaIndraja** [comment]
Sir I have already login the admin. But don't show the available train
part. Sir can you please give the available trains code once again. Sir I
will create available trains folder or not already code in the project. Sir
if your free sir can you please send the code in the the demo vedio shows.
Can you provide the demo vedio shows the code sir

**Comment by MurakondaIndraja** [comment]
Sir I have already registered as a admin. But i didn't know how to add the
trains and also I didn't understand where should I do modifications
according to that demo vedio. Could you please guide me according to that
demo vedio when your free sir.  Other wise if you don't mind could you
please send the required code sir.
